name: insightrag

include:
  - path:
      - ./data/compose.yaml
      - ./storage/compose.yaml
#    env_file: ./.env

networks:
  insightrag_net:
    name: insightrag_net
    driver: bridge

services:
  api-gateway:
    image: alpine:latest
    container_name: insightrag-gateway
    restart: on-failure
    networks:
      - insightrag_net

