CREATE CONSTRAINT c_chunk_id IF NOT EXISTS FOR (c:DocumentChunk) REQUIRE c.chunk_id IS UNIQUE;
CREATE CONSTRAINT c_node_id IF NOT EXISTS FOR (n:Node) REQUIRE n.id IS UNIQUE;
CREATE CONSTRAINT c_document_id IF NOT EXISTS FOR (d:Document) REQUIRE d.document_id IS UNIQUE;

