services:
  neo4j:
    image: neo4j:${GRAPH_VERSION:-2026.07.1}
    container_name: neo4j-server
    env_file:
      - ../.env
    volumes:
      - neo4j_data:/data
      - neo4j_conf:/conf
      - neo4j_logs:/logs
    environment:
      - NEO4J_AUTH=neo4j/${GRAPH_PASSWORD:-neo4jpassword}
      - NEO4J_PLUGINS=["apoc"]
    ports:
      - "7474:7474"
      - "7687:7687"
    restart: always

volumes:
  neo4j_data:
  neo4j_conf:
  neo4j_logs:
