spring.application.name=core-infrastructure
minio.endpoint=http://127.0.0.1:9000
minio.credentials.username=minioadmin
minio.credentials.password=miniopassword
minio.bucket.exchange.name=minio_buckets_events
minio.bucket.exchange.type=direct