spring.application.name=insightrag-retrieval
spring.config.import=optional:file:../.env[.properties]
#threading
spring.threads.virtual.enabled=true
#embedding
insightrag.tei.url=${TEI_URL:http://localhost:8081}
#gemini service
insightrag.ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta
insightrag.ai.gemini.model-main=${GEMINI_MODEL_MAIN:gemini-3-flash-preview}
insightrag.ai.gemini.model-lite=${GEMINI_MODEL_LITE:gemini-3.1-flash-lite}
insightrag.ai.gemini.model-tokenizer=${GEMINI_LOCAL_TOKENIZER:gemini-3-pro-preview}
insightrag.ai.gemini.api-key=${GEN_AI_API_KEY:mock-api-key}
insightrag.ai.gemini.max-history-token=4000
insightrag.ai.gemini.fallback.input-limit=32000
insightrag.ai.gemini.fallback.output-limit=8192
insightrag.ai.gemini.memory.max-session=5000
insightrag.ai.gemini.memory.ttl-minutes=60
insightrag.ai.gemini.query-limit-token=2000
#Neo4j
org.neo4j.migrations.enabled=false
spring.neo4j.uri=bolt://localhost:7687
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4jpassword
#spring doc


