spring.application.name=insightrag-retrieval
spring.config.import=optional:file:../.env[.properties]
#threading
spring.threads.virtual.enabled=true
#embedding
insightrag.embedding.infinity-url=${INFINITY_URL:http://localhost:8081}
insightrag.embedding.model=AITeamVN/Vietnamese_Embedding
#gemini service
insightrag.ai.gemini.base-url=https://generativelanguage.googleapis.com/v1beta
insightrag.ai.gemini.model-main=${GEMINI_MODEL_MAIN:gemini-3-flash-preview}
insightrag.ai.gemini.model-lite=${GEMINI_MODEL_LITE:gemini-3.5-flash-lite}
insightrag.ai.gemini.model-tokenizer=${GEMINI_LOCAL_TOKENIZER:gemini-3-pro-preview}
insightrag.ai.gemini.api-key=${GEN_AI_API_KEY:mock-api-key}
insightrag.ai.gemini.query-limit-token=2000
insightrag.ai.gemini.max-history-token=4000
insightrag.ai.gemini.fallback.input-limit=32000
insightrag.ai.gemini.fallback.output-limit=8192
insightrag.ai.gemini.memory.max-session=5000
insightrag.ai.gemini.memory.ttl-minutes=60
#context
insightrag.context.retrieval-timeout-seconds=60
insightrag.context.active-strategy=HYBRID
insightrag.context.strategies.HYBRID.chunk-limit=3
insightrag.context.strategies.HYBRID.node-limit=3
insightrag.context.strategies.HYBRID.relationship-limit=3
insightrag.context.strategies.DOCUMENT_HEAVY.chunk-limit=5
insightrag.context.strategies.DOCUMENT_HEAVY.node-limit=1
insightrag.context.strategies.DOCUMENT_HEAVY.relationship-limit=1
#Neo4j
org.neo4j.migrations.enabled=false
spring.neo4j.uri=${NEO4J_URI:bolt://localhost:7687}
spring.neo4j.authentication.username=neo4j
spring.neo4j.authentication.password=neo4jpassword
#Neo4j custom
insightrag.neo4j.search.tuning.rrf-constant=60
insightrag.neo4j.search.tuning.weight-fullText=1.0
insightrag.neo4j.search.tuning.weight-vector=1.0
insightrag.neo4j.search.tuning.min-vector-score=0.85
insightrag.neo4j.search.tuning.edge-semantic-guardrail=0.40
#transactional
spring.transaction.default-timeout=60
#logging
logging.level.com.hieulc.insightragretrieval.repository=DEBUG
#logging.level.org.neo4j.driver=DEBUG
logging.level.org.springframework.data.neo4j.cypher.unrecognized=OFF





